"""Resolve the companies in the store to live ATS boards, and remember the answer.

The store knows ~3,000 employers by name, but a name is not a feed: the depth lane
needs an (ats, slug) key before it can pull a company's whole board. This module
closes that gap — for every company without a resolution, try to find its board,
then WRITE DOWN WHAT HAPPENED either way.

Recording the failures is what makes this affordable. Most of those employers are
federal agencies, hospitals, and staffing firms that will never have a Greenhouse
board; without a negative cache every run re-probes all of them forever. With one,
a run only touches companies it has never seen, so this can ride along with the
nightly harvest instead of needing its own schedule.

Two lanes, most-trustworthy first:

  1. MATCH  — the company's name against the COMMITTED board universe
              (`deploy/board-universe.json`, see universe.py). The slug is real by
              construction — a crawler saw the URL — so the probe just confirms it.
  2. GUESS  — normalized variants of the name (see job_radar.discover.name_variants).
              Deliberately conservative: full-name forms only, never a bare first
              word, because `Capital One` -> `capital` resolves to a REAL board
              owned by someone else and the probe cannot tell the difference.

Nothing is written without a live probe returning >=1 role, and every resolution
stores the variant that won so a bad one can be found and undone.
"""

from __future__ import annotations

import argparse
from itertools import zip_longest

from job_radar import config, discover

from . import store
from . import universe as universe_file
from .snapshot import load_dotenv

# `MINE_LIMIT` / `JOBFITR_CDX_MINE_LIMIT` is GONE, and its removal is the point of this
# change rather than a tidy-up. It capped CDX *rows*, not boards, and CDX returns rows
# SURT-sorted — so it was an alphabetical truncation dressed as a budget, and every mine
# this project ever ran saw only the A-B head (one crawl holds 55,626
# `*.myworkdayjobs.com` rows; a 4,000-row cap returned 158 boards, `2020companies` through
# `baxter`). The universe now comes from a committed file generated by SQL over the columnar
# index, where there is no row cap to set. A surviving constant would imply one exists.

# Which ATSs the committed universe is asked for. Two of these four cannot currently be in
# it, and asking anyway is DELIBERATE: `universe.for_ats` raises `UniverseNotQueried` for a
# missing one and the caller prints it, so the nightly log carries a line per dark lane
# instead of a silence.
#
#   greenhouse, ashby — mined; the live hosts are job-boards.greenhouse.io and
#                       jobs.ashbyhq.com.
#   lever            — CAN NEVER BE MINED. jobs.lever.co/robots.txt sets `User-agent: CCBot`
#                      / `Disallow: /`, and Common Crawl honors it, so no crawl will ever
#                      contain a Lever board (the boards are live — /matchgroup returns 200 —
#                      the crawler is forbidden). jobfitr's 179 Lever resolutions all came
#                      from name-guessing and always will.
#   workday          — withheld, on measurement: 57% of its "US-servable" rows are
#                      unverifiable-foreign. Its three-part key (tenant, wdN host, site slug)
#                      is unguessable from a company name, so the crawl is the ONLY route to
#                      the enterprise/government/healthcare tier — which is why the read path
#                      stays wired for when a location normalizer lands.
CDX_ATS = ["greenhouse", "lever", "ashby", "workday"]
# What a company NAME can be guessed into — single-key ATSs only.
GUESSABLE_ATS = ["greenhouse", "lever", "ashby"]


def resolve_batch(
    limit: int = 500,
    use_cdx: bool = False,
    ats_list: list[str] | None = None,
    workers: int = 8,
    path: str | None = None,
) -> dict:
    """Resolve up to `limit` unresolved companies; persist every outcome.

    Returns a summary dict. `use_cdx=True` additionally matches names against the
    committed board universe — much higher precision than guessing, because the slug came
    from a URL a crawler actually saw. (The flag keeps its old name: it no longer touches
    Common Crawl at request time, but it is the same lane, and renaming a CLI flag people
    have in their shell history buys nothing.)
    """
    names = store.unresolved_companies(limit=limit, path=path)
    if not names:
        return {"checked": 0, "resolved": 0, "unresolved": 0}

    known = {
        (c["ats"], (c["slug"] or "").lower())
        for c in store.resolved_companies(path=path)
    }
    found: dict[str, dict] = {}

    universe_error = ""
    dark_lanes: list[str] = []
    if use_cdx:
        # Reads the COMMITTED universe, not a live mine. NOTE: no `path=` here — this
        # function's `path` is the DATABASE path, and handing it to the universe loader
        # would look plausible and silently find no boards.
        #
        # Reported, not raised: a missing universe must not take down name-guessing, which
        # is the lane that does most of the work. But it is never a silent zero — the
        # caller prints `universe_error`, because "the file is missing" and "the crawl knew
        # of no new boards" are different events that used to look identical.
        # CONTINUE, never break. An earlier draft broke on the first failure, which was a
        # live bug the moment `for_ats` learned to raise for an un-mined ATS: `CDX_ATS` is
        # [greenhouse, lever, ashby, workday], lever can never be mined, so breaking on it
        # meant ASHBY WAS NEVER READ — 2,629 boards silently skipped by an error handler.
        universe = []
        errs, dark = [], []
        for ats in ats_list or CDX_ATS:
            try:
                universe.extend(universe_file.for_ats(ats))
            except universe_file.UniverseNotQueried:
                # EXPECTED vs UNEXPECTED, and the split is the point. lever and workday are
                # absent by design and always will be, so folding them into `universe_error`
                # made a ⚠ fire on every healthy night — and a warning that is always on is
                # this project's signature bug in a fourth costume: nobody reads it, so when
                # the file genuinely goes missing the message that matters is invisible
                # inside the message that always appears.
                (dark if ats in universe_file.EXPECTED_ABSENT else errs).append(ats)
            except universe_file.UniverseUnavailable as e:
                # The FILE is gone — no later ATS can succeed either, so stop asking.
                errs.append(str(e))
                break
        universe_error = "; ".join(errs)
        dark_lanes = list(dark)
        # Matching a NAME against the mined universe is the only way Workday is
        # reachable at all: its site slug ('BWCareers', 'Agent-Staff') cannot be
        # guessed from a company name, but CDX saw the whole tenant/host/site triple,
        # so a name that matches the tenant inherits the other two. That is the entire
        # non-tech tier — insurance, manufacturing, municipalities, national labs.
        for e in discover.match_known(names, universe):
            found.setdefault(e["name"], e)

    # Name-guessing for whatever the CDX match didn't cover. Deliberately NOT Workday:
    # a guessed tenant without the right site slug is a wasted request, not a company.
    outcomes: list[dict] = []
    remaining = [n for n in names if n not in found]
    if remaining:
        for e in discover.from_names(
            remaining,
            ats_list=[a for a in (ats_list or GUESSABLE_ATS) if a != "workday"],
            known=known,
            workers=workers,
            outcomes=outcomes,
        ):
            found.setdefault(e["name"], e)

    # A board that REFUSED us (401/403) is not "we found nothing" — it exists and has
    # said no. Recording that as `dead` stops the nightly scheduler asking again
    # forever, which is both pointless and impolite.
    refused = {
        o["name"]
        for o in outcomes
        if o.get("outcome") == "refused" and o.get("name") and o["name"] not in found
    }

    # A name whose every candidate was SKIPPED is not a name that was answered — and this
    # is the defect that made 377 companies simultaneously resolved and unresolved.
    #
    # `discover.from_names` receives `known` and does `if key in known: continue`, so when a
    # company's guessed slug is already resolved (typically as `board:{ats}:{slug}`, since a
    # board slug IS a normalized company name), NO candidate is generated, the name never
    # lands in `found`, and it falls through to `record_resolution(name, None)` — a 90-DAY
    # NEGATIVE written against a company we have already solved. That is why `attempts` is 1
    # on 7,937 of 7,940 ledger rows.
    #
    # This change makes it 5.5x worse if left alone: `known` grows from ~1,390 keys to
    # ~7,600 once the committed universe lands, so far more store companies collide.
    #
    # The fix is deliberately CONSERVATIVE — treat the name as indeterminate rather than
    # binding it to the colliding board. Binding would reintroduce exactly the
    # `Capital One` -> `capital` false-binding class that `name_variants` refuses to risk;
    # the collision is strong evidence but not proof, and a wrong board floods the store
    # with another company's jobs. So: do not claim, do not lie either.
    skipped_as_known = set()
    for name in remaining:
        try:
            # aggressive=True UNCONDITIONALLY, to mirror `from_names`, which passes
            # `aggressive=(ats in _IDENTITY_URL)` — True for greenhouse, adding the
            # bare-first-word variant. Measured on the 176 names a real nightly batch
            # returns: the faithful detector finds 37 collisions, a non-aggressive one finds
            # 34, missing `Future Caucus` (collides on greenhouse/future), `Oura Health Ltd`
            # and `Stellar Tech` — an 8% under-detection. Over-detecting is the benign
            # direction here: the result only ever WITHHOLDS a negative-cache write, and it
            # only fires when nothing was found anyway.
            variants = discover.name_variants(name, aggressive=True)
        except Exception:  # noqa: BLE001 — a name we cannot normalize is simply not skipped
            continue
        for ats in (a for a in (ats_list or GUESSABLE_ATS) if a != "workday"):
            if any((ats, v.lower()) in known for v in variants):
                skipped_as_known.add(name)
                break

    # A name we never got a real ANSWER for must not be cached as a 90-day negative.
    # probe() deliberately marks a 429 `throttled` (retryable) and a network fault
    # `error`, precisely so a rate-limited sweep — which the code's own comments say
    # "reliably trips" at volume — is not mistaken for "this company has no board." If
    # ANY of a name's candidates came back throttled/error, we didn't finish probing
    # it: leave it never-checked so tonight's run retries, rather than freezing it out
    # of discovery for a quarter over one bad night.
    indeterminate = {
        o["name"]
        for o in outcomes
        if o.get("outcome") in ("throttled", "error") and o.get("name")
    }
    # Parenthesized deliberately. `-` binds tighter than `|`, so `A | B - found - refused`
    # silently means `A | (B - found - refused)`, leaving names in the set that were actually
    # resolved. Today that is HARMLESS rather than a bug — the write loop's guard is
    # `if not entry and name in indeterminate`, so a resolved company cannot reach the
    # `continue` however this set is built (verified by mutation: removing the parentheses
    # changes no test outcome). The parentheses are here so the expression means what it
    # reads as, and so a future refactor that drops the `not entry` guard does not turn a
    # cosmetic precedence quirk into a real one.
    # `skipped_as_known` is NOT folded into `indeterminate`. That was the first fix and it
    # traded a false negative for an unbounded retry loop: `indeterminate` means "write
    # nothing, try again tomorrow", and this set goes from 4 names to 37 of every 176-name
    # batch (21%) once the committed universe grows `known`. `unresolved_companies` orders by
    # JOB COUNT, so 37 permanent residents would crowd the biggest employers into a
    # `limit=500` queue slot forever and never converge.
    #
    # These names have a real, TERMINAL answer that claims no ownership: the guessable slug
    # space for this name is already held by a resolved board, so guessing cannot produce
    # anything new. `status='covered'` records exactly that. It is terminal for free —
    # `unresolved_companies` retries only `status=='unresolved'` — and it makes the
    # `board:`-vs-name duplication legible in `--stats` instead of looking like a permanent
    # unresolved backlog. Crucially it still binds NO board, so the `Capital One` -> `capital`
    # class stays impossible.
    covered = skipped_as_known - set(found) - refused
    indeterminate = indeterminate - set(found) - refused - covered

    # The apply URLs we already hold are an independent statement of who owns which
    # board — and the ONLY ownership check that reaches Ashby and Lever, which expose
    # no company name. A candidate contradicted by a company's own links is rejected
    # here rather than written and audited later. Measured: this catches bindings the
    # Greenhouse name check structurally cannot, e.g. "Runway" -> ashby/runway (4
    # roles, an FP&A startup) when its own postings link to ashby/runway-ml (41 roles).
    evidence = store.board_evidence(path=path)
    contradicted = []
    for name, e in list(found.items()):
        seen = evidence.get(store.norm_company(name))
        if seen and (e["ats"], (e["slug"] or "").lower()) not in seen:
            contradicted.append((name, e, sorted(seen)))
            del found[name]

    for name in names:
        entry = found.get(name)
        if not entry and name in indeterminate:
            continue  # never got a real answer — retry next run, don't cache
        cache_status = None
        if not entry:
            if name in refused:
                cache_status = "dead"
            elif name in covered:
                cache_status = "covered"
        store.record_resolution(
            name,
            entry,
            variant=(entry or {}).get("slug", ""),
            status=cache_status,
            path=path,
        )

    return {
        "universe_error": universe_error,
        "dark_lanes": dark_lanes,
        "covered": len(covered),
        "checked": len(names),
        "resolved": len(found),
        "dead": len(refused),
        "contradicted": len(contradicted),
        "deferred": len(indeterminate),
        "unresolved": len(names) - len(found) - len(refused) - len(indeterminate),
    }


def discover_new(
    ats_list: list[str] | None = None,
    workers: int = 8,
    path: str | None = None,
    budget: int = 500,
) -> dict:
    """Add companies we have NEVER heard of, from the committed board universe.

    The mirror image of resolve_batch, and the half that actually carries the
    non-tech tier. resolve_batch walks employers already in the store and asks "does
    this one have a board?" — so it can only ever find companies an aggregator
    already showed us. But the Workday universe (Barry-Wehmiller, Argonne, Baltimore
    City, Ace Hardware) never appears in the store at all: those employers do not
    syndicate to the free boards, which is precisely why they are missing. Matching
    names against the crawl cannot reach them, because there is no name to match.

    So this goes the other way: read every board the crawl says exists, drop the ones
    already in the ledger, probe the rest, and keep what answers. No identity check —
    there is no company name to verify against, and none is claimed; the company name
    arrives with the jobs themselves. That is also why this is the SAFEST lane rather
    than the riskiest: with no name being bound, the `Capital One` -> `capital`
    false-binding class (see discover.name_variants) is impossible here by construction.
    """
    known = {
        (c["ats"], (c["slug"] or "").lower(), (c.get("site") or "").lower())
        for c in store.resolved_companies(path=path)
    }
    # PLUS every board already probed recently, whatever the answer was. Without this the
    # non-answers below are invisible to the next run, a 404 stays at the head of the queue
    # forever, and discovery oscillates over the same tranche instead of converging. The
    # retry window is `store.UNRESOLVED_RETRY_DAYS`, so a board that was dead in July still
    # gets one more look in October.
    known |= store.recently_probed_boards(path=path)
    candidates, mine_errors, dark_lanes = [], [], []
    for ats in ats_list or CDX_ATS:
        try:
            mined = universe_file.for_ats(ats)
        except universe_file.UniverseNotQueried:
            # Expected-dark by design (see universe.EXPECTED_ABSENT) — informational, not a
            # warning. Only an unexpected absence or a missing FILE earns the ⚠ below.
            if ats in universe_file.EXPECTED_ABSENT:
                dark_lanes.append(ats)
            else:
                mine_errors.append(f"{ats}: not mined")
            continue
        except universe_file.UniverseUnavailable as e:
            # Kept as a reported condition rather than a raise for the same reason the live
            # mine's errors were: one missing input must not kill a sweep that still has
            # name-resolution work to do. But it is REPORTED — `mined 0 unknown boards`
            # silently meaning "we were refused" is the bug this whole module replaced.
            # Prefixed with the ATS on purpose: the diagnostic value is knowing WHICH
            # lanes went dark, not just that one did.
            mine_errors.append(f"{ats}: {e}")
            continue
        for c in mined:
            key = (c["ats"], c["slug"].lower(), (c.get("site") or "").lower())
            if key not in known:
                known.add(key)
                candidates.append(c)

    # A PER-RUN PROBE BUDGET, and it is not politeness theatre.
    #
    # `resolve_batch` has always had `limit=500`; this function had none, because until the
    # committed universe landed it had nothing to probe (Common Crawl refused the box, so
    # `candidates` was always empty). With the universe it is ~6,200 unknown boards in one
    # run, against an API whose own comments say a few-hundred-candidate sweep "reliably
    # trips" the rate limiter — and a throttled candidate is never cached, so the whole
    # tranche would come back tomorrow.
    #
    # The harder ceiling is RAM, not the API. `[live prod]` the box has 3,233 MB available
    # with jobfitr-web@green alone at 2.58 GB, `jobs.json` is already 330 MB, and both
    # `snapshot.py` and `store.py` do `json.loads(p.read_text())` — the whole file as bytes,
    # then as str, then as objects. Opening the tap on 6,200 boards at once risks an
    # OOM-kill mid-harvest, which leaves the pool frozen while every dashboard reads healthy
    # — the exact `pool_size` vs `snapshot_count` regression /api/health exists to catch.
    #
    # 500/night walks the whole universe in a fortnight and lets `jobs.json` be measured as
    # it grows. Raise it only with a measurement of bytes-per-added-board in hand.
    over_budget = max(0, len(candidates) - budget)
    if over_budget:
        # ROUND-ROBIN BY ATS, not `candidates[:budget]`.
        #
        # `candidates` is built in `CDX_ATS` order over slug-sorted `for_ats` output, so a
        # head slice is the SAME first N greenhouse slugs every night — an alphabetical
        # truncation dressed as a RAM guard, which is the precise sin `MINE_LIMIT` was
        # deleted for. Interleaving the ATSs at least spends the budget across every lane
        # instead of parking it in greenhouse's A-tranche.
        #
        # Interleaving alone does NOT make the window advance — that is what caching the
        # non-answers below is for. The two are one fix: round-robin decides WHERE the window
        # sits, the cache is what lets it MOVE.
        by_ats: dict[str, list[dict]] = {}
        for c in candidates:
            by_ats.setdefault(c["ats"], []).append(c)
        interleaved = []
        for tranche in zip_longest(*by_ats.values()):
            interleaved.extend(c for c in tranche if c is not None)
        candidates = interleaved[:budget]

    outcomes: list[dict] = []
    verified = discover.probe(candidates, workers=workers, outcomes=outcomes)
    for e in verified:
        store.record_resolution(
            _board_name(e), e, variant="cdx-discovery", key=board_key(e), path=path
        )
    # ONLY a hard refusal is terminal. A 429 is the rate limiter asking us to slow
    # down — recording that as dead would blacklist good employers wholesale, since
    # sweeping a few hundred Workday tenants reliably trips it.
    refused = [o for o in outcomes if o.get("outcome") == "refused"]
    for o in refused:
        store.record_resolution(
            _board_name(o), None, status="dead", key=board_key(o), path=path
        )
    # RECORD THE NON-ANSWERS. `missing` (404), `empty` (a real board with no open roles),
    # `wrong-owner` and `unsupported` are all real answers, and until now none of them were
    # written anywhere — only `verified` and `refused` produced a row. So every 404 in the
    # universe came back for another probe every single night, forever.
    #
    # They are written as ordinary `unresolved` rows on the `board:` key, which means
    # `UNRESOLVED_RETRY_DAYS` gives them one more look per quarter — right for `empty`
    # especially, since a board with no roles today may post tomorrow. Deliberately NOT keyed
    # to the crawl id: a new crawl landing is no evidence that a dead board came alive.
    #
    # `throttled` and `error` are excluded — those are not answers. Caching them would
    # blacklist good boards over one bad night, the same trap `resolve_batch` documents.
    non_answers = [
        o
        for o in outcomes
        if o.get("outcome") in ("missing", "empty", "wrong-owner", "unsupported")
    ]
    for o in non_answers:
        store.record_resolution(_board_name(o), None, key=board_key(o), path=path)

    throttled = sum(1 for o in outcomes if o.get("outcome") == "throttled")
    return {
        "mined": len(candidates),
        "deferred_over_budget": over_budget,
        "added": len(verified),
        "dead": len(refused),
        "cached_non_answers": len(non_answers),
        "throttled": throttled,
        "roles": sum(e.get("roles", 0) for e in verified),
        "mine_errors": mine_errors,
        "dark_lanes": dark_lanes,
    }


def _board_name(entry: dict) -> str:
    """The DISPLAY name of a discovered BOARD (what shows in the ledger's `name`)."""
    if entry.get("ats") == "workday" and entry.get("site"):
        return f"{entry['slug']}/{entry['site']}"
    return entry.get("name") or entry["slug"]


def board_key(entry: dict) -> str:
    """The ledger PRIMARY KEY for a discovered board.

    Deliberately in its own `board:` namespace. A discovered board is identified by
    what it IS (ats + slug), not by a company name we don't have — and it must never
    share a key with a name-resolved company, because a company's slug is its own
    normalized name (see discover.name_variants), so board slugs and company names
    would collide by construction. Workday tenants run several boards (Ace Hardware:
    External, ARG_External, AHHS_External), so the site is part of the key too.
    """
    ats, slug = entry.get("ats", ""), entry.get("slug", "")
    if ats == "workday" and entry.get("site"):
        return f"board:workday:{slug}/{entry['site']}"
    return f"board:{ats}:{slug}"


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(
        prog="jobfitr-resolve",
        description="Resolve store companies to live ATS boards; cache both outcomes.",
    )
    ap.add_argument("--limit", type=int, default=500, help="companies to check")
    ap.add_argument(
        "--cdx",
        action="store_true",
        help="also mine Common Crawl and match names against it (slower, better)",
    )
    ap.add_argument(
        "--discover",
        action="store_true",
        help="add NEW companies from Common Crawl that the store has never seen "
        "(the only route to the Workday/enterprise tier)",
    )
    ap.add_argument(
        "--discover-budget",
        type=int,
        default=500,
        help="boards to PROBE per --discover run (default 500). The ceiling is NOT the probe — "
        "measured 150 MB and 97 s per 500 — it is what the nightly HARVEST then has to poll, "
        "since every resolved board is polled every night forever. Raise it deliberately and "
        "measure the harvest's MemoryPeak afterwards.",
    )
    ap.add_argument("--workers", type=int, default=8)
    ap.add_argument("--stats", action="store_true", help="print ledger state and exit")
    ap.add_argument(
        "--audit",
        action="store_true",
        help="re-check existing resolutions against apply-URL evidence and report",
    )
    ap.add_argument(
        "--quarantine",
        action="store_true",
        help="with --audit: retract the contradicted resolutions",
    )
    args = ap.parse_args(argv)

    load_dotenv()
    config.set_active(config.load_config(None))
    store.init()

    if args.stats:
        s = store.resolution_stats()
        print(
            f"companies in store: {s['companies_in_store']:,}  "
            f"resolved: {s['resolved']:,}  unresolved: {s['unresolved']:,}  "
            f"dead: {s.get('dead', 0):,}  never checked: {s['never_checked']:,}"
        )
        return 0

    if args.audit:
        a = store.audit_resolutions()
        print(
            f"audit: {a['checked']:,} resolutions have apply-URL evidence -> "
            f"{a['agree']:,} agree, {len(a['disagree']):,} CONTRADICTED"
        )
        for d in a["disagree"]:
            says = ", ".join(f"{x[0]}/{x[1]}" for x in d["url_says"][:3])
            print(
                f"   {d['name'][:30]:32} we say {d['ats']}/{d['slug']:<22} "
                f"its links say {says}  (variant={d['matched_variant']})"
            )
        if a["disagree"] and args.quarantine:
            for d in a["disagree"]:
                store.quarantine(d["name"], reason=f"url-says:{d['url_says'][0][1]}")
            print(f"   -> quarantined {len(a['disagree'])} contradicted resolution(s)")
        elif a["disagree"]:
            print("   -> re-run with --quarantine to retract them")
        return 0

    if args.discover:
        # Say WHERE the universe came from and HOW OLD it is, every run. The file is
        # refreshed by a monthly human step, and a human step that is skipped silently is
        # the same class of bug as the mine that logged `0` when it had been refused.
        try:
            print(f"  {universe_file.describe()}")
        except universe_file.UniverseUnavailable as e:
            print(f"  ⚠ {e}")
        d = discover_new(workers=args.workers, budget=args.discover_budget)
        print(
            f"jobfitr-discover: mined {d['mined']:,} unknown boards -> "
            f"{d['added']:,} added ({d['roles']:,} roles), {d['dead']:,} refused, "
            f"{d['throttled']:,} throttled"
        )
        if d["dark_lanes"]:
            # Plain, not a warning: these lanes are dark on purpose and every night.
            print(
                f"  universe: {', '.join(d['dark_lanes'])} not mined by design "
                f"(expected — see jobfitr/universe.py)"
            )
        if d["mine_errors"]:
            # LOUD: a discovery run that read nothing because the universe file is missing
            # is a completely different event from one that found nothing new. This used to
            # say "Common Crawl unreachable", which was true of the live mine and is now
            # impossible — production no longer talks to Common Crawl at all.
            print(
                f"  ⚠ board universe unavailable for {len(d['mine_errors'])} ATS(s): "
                f"{'; '.join(d['mine_errors'])}"
            )
            print("    → no new companies were discovered this run.")

    r = resolve_batch(limit=args.limit, use_cdx=args.cdx, workers=args.workers)
    if r.get("universe_error"):
        print(f"  ⚠ {r['universe_error']}")
        print("    → name-matching was SKIPPED this run; guessing still ran.")
    if r.get("covered"):
        print(
            f"  {r['covered']:,} company(s) marked 'covered' — their guessable slug space is "
            f"already held by a resolved board, so guessing cannot help"
        )
    print(
        f"jobfitr-resolve: checked {r['checked']:,} companies -> "
        f"{r['resolved']:,} resolved, {r['dead']:,} dead, "
        f"{r['unresolved']:,} cached as unresolved"
    )
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
