#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# jobfitr — the SLOT SWAP. Promotes the staging (inactive) slot to production and
# demotes the old production to staging. Atomic and instantly reversible: run it
# again to roll back. Zero downtime — `caddy reload` is a graceful config swap.
#
#   sudo bash flip.sh            # swap prod <-> staging
#
# The one source of truth for "which slot is live" is /etc/jobfitr/active-slot.
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

STATE=/etc/jobfitr/active-slot
SNIPPET=/etc/caddy/jobfitr-slots.caddy

port_of() { [[ "$1" == blue ]] && echo 8000 || echo 8001; }

active=$(cat "$STATE" 2>/dev/null || echo blue)          # current production slot
if [[ "$active" == blue ]]; then promote=green; else promote=blue; fi

prod_port=$(port_of "$promote")   # the slot becoming production
stag_port=$(port_of "$active")    # the slot becoming staging

# Always rewrite the prod block: jobfitr.app → the promoted slot.
# (Caddyfile syntax requires block bodies on their own lines — an inline
#  `handle { directive }` on one line is rejected by the adapter.)
cat >"$SNIPPET" <<EOF
# GENERATED by flip.sh — do not edit by hand. active(prod)=$promote  staging=$active
jobfitr.app {
	encode gzip zstd
	handle /api/* {
		reverse_proxy 127.0.0.1:${prod_port}
	}
	handle {
		root * /opt/jobfitr/${promote}/jobfitr/web
		file_server
	}
}
EOF

# The staging block is emitted ONLY when staging.jobfitr.app actually resolves —
# otherwise Caddy would try (and fail) to issue a Let's Encrypt cert for a DNS name
# that doesn't exist, erroring the reload. Add the DNS record (Phase 2) and the next
# flip picks up the preview URL automatically. The flip itself never needs staging.
if getent hosts staging.jobfitr.app >/dev/null 2>&1; then
	cat >>"$SNIPPET" <<EOF
staging.jobfitr.app {
	encode gzip zstd
	handle /api/* {
		reverse_proxy 127.0.0.1:${stag_port}
	}
	handle {
		root * /opt/jobfitr/${active}/jobfitr/web
		file_server
	}
	# import staging-auth   # uncomment to password-protect the preview
}
EOF
	staging_line="            staging (staging.jobfitr.app) → ${active} (:${stag_port})"
else
	staging_line="            staging URL not configured (no staging.jobfitr.app DNS) — inactive slot ${active} idles on :${stag_port}"
fi

# Graceful, zero-downtime reload (in-flight requests finish on the old config).
systemctl reload caddy

echo "$promote" >"$STATE"
echo "✔ flipped — production (jobfitr.app) → ${promote} (:${prod_port})"
echo "$staging_line"
echo "  roll back with: sudo bash flip.sh"
