#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# jobfitr — the SLOT SWAP. Promotes the staging (inactive) slot to production and
# demotes the old production to staging. Atomic and instantly reversible: run it
# again to roll back. Zero downtime — `caddy reload` is a graceful config swap.
#
#   sudo bash flip.sh            # swap prod <-> staging
#
# The one source of truth for "which slot is live" is /etc/jobfitr/active-slot.
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

STATE=/etc/jobfitr/active-slot
SNIPPET=/etc/caddy/jobfitr-slots.caddy

port_of() { [[ "$1" == blue ]] && echo 8000 || echo 8001; }

active=$(cat "$STATE" 2>/dev/null || echo blue)          # current production slot
if [[ "$active" == blue ]]; then promote=green; else promote=blue; fi

prod_port=$(port_of "$promote")   # the slot becoming production
stag_port=$(port_of "$active")    # the slot becoming staging

# Rewrite the two site blocks: prod → the promoted slot, staging → the demoted one.
cat >"$SNIPPET" <<EOF
# GENERATED by flip.sh — do not edit by hand. active(prod)=$promote  staging=$active
jobfitr.app {
	encode gzip zstd
	handle /api/* { reverse_proxy 127.0.0.1:${prod_port} }
	handle { root * /opt/jobfitr/${promote}/jobfitr/web; file_server }
}
staging.jobfitr.app {
	encode gzip zstd
	handle /api/* { reverse_proxy 127.0.0.1:${stag_port} }
	handle { root * /opt/jobfitr/${active}/jobfitr/web; file_server }
	# import staging-auth   # uncomment to password-protect the preview
}
EOF

# Graceful, zero-downtime reload (in-flight requests finish on the old config).
systemctl reload caddy

echo "$promote" >"$STATE"
echo "✔ flipped — production (jobfitr.app) → ${promote} (:${prod_port})"
echo "            staging (staging.jobfitr.app) → ${active} (:${stag_port})"
echo "  roll back with: sudo bash flip.sh"
